# Generated by Django 4.2.7 on 2024-01-21 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question',
            new_name='level',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='test_suite',
            new_name='level',
        ),
    ]
